# -*- coding: utf-8 -*-
"""Daily NewsLetter BOT - GH version

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tG_l2GH8aUmhlWJ6fVN_RQnwNKNsXy6
"""
import os
import requests
import pandas as pd
import feedparser
from difflib import SequenceMatcher
from datetime import datetime
from openai import OpenAI
import smtplib
from email.mime.text import MIMEText


# RSS sources
rss_feeds = {
    "Reuters World": "http://feeds.reuters.com/Reuters/worldNews",
    "Reuters Business": "http://feeds.reuters.com/reuters/businessNews",
    "TechCrunch": "https://techcrunch.com/feed/",
    "Google News World": "https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en"
}

headlines = []

for source, url in rss_feeds.items():
    feed = feedparser.parse(url)

    for entry in feed.entries:
        headlines.append({
            "source": source,
            "title": entry.title,
            "link": entry.link
        })

df = pd.DataFrame(headlines)

print("Total headlines fetched:", len(df))
df.head(10)

from difflib import SequenceMatcher

# Function to calculate similarity
def similarity(a, b):
    return SequenceMatcher(None, a, b).ratio()

unique_headlines = []

for title in df["title"]:

    is_duplicate = False

    for existing in unique_headlines:
        if similarity(title, existing) > 0.8:
            is_duplicate = True
            break

    if not is_duplicate:
        unique_headlines.append(title)

clean_df = pd.DataFrame(unique_headlines, columns=["title"])

print("Original headlines:", len(df))
print("Unique headlines:", len(clean_df))

clean_df.head(10)

import os
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Convert headlines into a numbered list
headline_list = "\n".join(
    [f"{i+1}. {title}" for i, title in enumerate(clean_df["title"].tolist()[:80])]
)

prompt = f"""
You are a global macro news analyst.

From the following list of headlines, select the 10 most important stories.

Focus on stories related to:
- global markets
- economic policy
- geopolitics
- technology shifts
- regulation

Ignore:
- celebrity news
- crime
- local events
- minor company announcements

Return ONLY the selected headlines.

Headlines:
{headline_list}
"""

response = client.chat.completions.create(
    model="gpt-5-mini",
    messages=[
        {"role": "system", "content": "You are a financial news analyst."},
        {"role": "user", "content": prompt}
    ],
)

important_news = response.choices[0].message.content

print(important_news)

analysis_prompt = f"""
You are a global macro analyst writing for a daily newsletter.

For each of the following news stories provide:

1. What happened (1-2 sentences)
2. Why it matters (1-2 sentences)
3. Potential market or geopolitical impact

Keep explanations concise and insightful.

Stories:
{important_news}
"""

response = client.chat.completions.create(
    model="gpt-5-mini",
    messages=[
        {"role": "system", "content": "You are an expert financial analyst."},
        {"role": "user", "content": analysis_prompt}
    ],
)

news_analysis = response.choices[0].message.content

print(news_analysis)

from datetime import datetime

today = datetime.now().strftime("%d %B %Y")

newsletter_prompt = f"""
You are writing a concise daily briefing newsletter called "Daily Capsule".

Use the analysis below and convert it into a clean newsletter.

Structure:

Daily Capsule
Date: {today}

Top Global Developments
- Present the key stories clearly

Technology Signals
- Highlight technology-related developments

Geopolitical & Market Impact
- Summarize major macro implications

Keep the writing sharp, clear and insightful.
Avoid repeating the same sentences.

Analysis:
{news_analysis}
"""

response = client.chat.completions.create(
    model="gpt-5-mini",
    messages=[
        {"role": "system", "content": "You are an editor of a global financial newsletter."},
        {"role": "user", "content": newsletter_prompt}
    ],
)

newsletter_text = response.choices[0].message.content

print(newsletter_text)

business_prompt = f"""
You are a sharp business analyst.

From the following news analysis, pick ONE interesting story related to:
- startups
- business strategy
- pivots
- product decisions
- growth tactics

Then provide:

1. What happened (2 lines max)
2. The real insight (not obvious)
3. A sharp takeaway someone can apply at work

Keep it crisp, non-generic, and insightful(a layman should be able to interpret).

News:
{news_analysis}
"""

response = client.chat.completions.create(
    model="gpt-5-mini",
    messages=[
        {"role": "system", "content": "You think like a startup operator."},
        {"role": "user", "content": business_prompt}
    ],
)

business_section = response.choices[0].message.content

print(business_section)

import requests

# Hyderabad coordinates
lat = 17.3850
lon = 78.4867

url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,weathercode&timezone=auto"

response = requests.get(url)
data = response.json()

# Extract values
temp_max = data["daily"]["temperature_2m_max"][0]
temp_min = data["daily"]["temperature_2m_min"][0]
precip_prob = data["daily"]["precipitation_probability_max"][0]
weather_code = data["daily"]["weathercode"][0]

weather_map = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Fog",
    51: "Light drizzle",
    53: "Moderate drizzle",
    55: "Heavy drizzle",
    61: "Light rain",
    63: "Moderate rain",
    65: "Heavy rain",
    80: "Rain showers",
    81: "Moderate showers",
    82: "Heavy showers",
    95: "Thunderstorm"
}

weather_desc = weather_map.get(weather_code, "Unknown")

weather_prompt = f"""
You are writing a sharp weather update for a daily newsletter.

Data:
Temperature: {temp_min}–{temp_max}°C
Rain probability: {precip_prob}%
Condition: {weather_desc}

Write:
1. Clean temperature range
2. One-line practical insight (timing, rain, productivity, outdoor plans)

Rules:
- Be specific (mention rain if relevant)
- Make it actionable
- Keep it crisp (2–3 lines max)
"""

response = client.chat.completions.create(
    model="gpt-5-mini",
    messages=[
        {"role": "system", "content": "You give practical daily insights."},
        {"role": "user", "content": weather_prompt}
    ],
)

weather_text = response.choices[0].message.content

print(weather_text)

quote_prompt = """
You are curating a 'Thought of the Day' for a sharp, ambitious audience.

Pick:
- A quote from a well-known thinker (business leader, philosopher, scientist, etc.)

Then provide:
The quote (1 line), Who said it
A simple interpretation (2–3 lines, practical, not philosophical fluff)

Rules:
- Avoid overused quotes
- Keep it fresh and meaningful
- Make interpretation applicable to work/life decisions
- Make the interpretation feel like advice from a smart mentor, not a philosopher.
"""

response = client.chat.completions.create(
    model="gpt-5-mini",
    messages=[
        {"role": "system", "content": "You think like a wise operator."},
        {"role": "user", "content": quote_prompt}
    ],
)

quote_section = response.choices[0].message.content

print(quote_section)

structured_prompt = f"""
You are writing a sharp, engaging daily newsletter for a Gen-Z audience.

Style:
- Short sentences
- Conversational tone
- No jargon
- Break lines frequently
- Easy to scan on phone
- Slight personality, but not cringe

Structure:

Daily Capsule
Date: {today}

🌤️ Weather — Hyderabad (Gachibowli)
{weather_text}

💡 Thought of the Day
{quote_section}

📊 Markets
Hook: A sharp one-line summary of what's happening in markets

- Each update in 1–2 lines
- Then: "Why it matters:" (1 line)

🧠 Technology
Hook: One-line takeaway

- Updates
- Why it matters

🌍 Geopolitics
Hook: One-line takeaway

- Updates
- Why it matters

Rules:
- Hooks should feel sharp and insightful (Don't mention as hook - just highlight as heading)
- No generic lines like "Markets are mixed"
- Make it feel like a strong opening line

Stories:
{news_analysis}
"""

response = client.chat.completions.create(
    model="gpt-5-mini",
    messages=[
        {"role": "system", "content": "You are a sharp financial editor."},
        {"role": "user", "content": structured_prompt}
    ],
)

structured_newsletter = response.choices[0].message.content

print(structured_newsletter)

import smtplib
from email.mime.text import MIMEText


# Your email details

import os

sender_email = os.getenv("SENDER_EMAIL")
receiver_emails = os.getenv("RECEIVER_EMAIL").split(",")
app_password = os.getenv("APP_PASSWORD")

# Create email
msg = MIMEText(structured_newsletter)
msg["Subject"] = "Daily Capsule"
msg["From"] = sender_email
msg["To"] = ", ".join(receiver_emails)

# Send email
server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
server.login(sender_email, app_password)
server.sendmail(sender_email, receiver_emails, msg.as_string())
server.quit()

print("✅ Newsletter sent successfully!")
